templateinherit/mysite/urls.py
from django.urls import path
from mysite import views

app_name = 'mysite'

urlpatterns = [
    path('dashboard/',views.about,name='dashboard'),
    path('about/',views.about,name='ab'),
    path('contact/',views.contactView,name='con'),
    path('studentForm/',views.studentForm,name='studentForm'),
    path('employeeForm/',views.empView,name='employeeForm'),
    path('uslogin/',views.uslogin,name='uslogin'),
    path('usregister1/',views.rgUsingMF,name='usregister1'),
    path('usregister/',views.usregister,name='usregister'),
    path('uslogout',views.uslogout,name='logout'),
    path('check_user',views.check_user,name='check_user'),
    path('change_password',views.change_password,name='change_password'),
    path('profile',views.profile,name='profile'),
    path('change_profile',views.change_profile,name='change_profile'),


]

templateinherit/templateinherit/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('mysite/',include('mysite.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templateinherit/mysite/forms.py
from django import forms
from mysite.models import employee
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.contrib.auth.models import User

class Student(forms.Form):
    GEN = (('m','male'),('f','female'))

    name = forms.CharField(required=False,widget=forms.TextInput(attrs={'placeholder':'Please Enter Name Here..','class':'bg-dark'}))
    roll_number = forms.IntegerField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    gender = forms.ChoiceField(choices=GEN)
    dob = forms.DateField(widget = forms.DateInput(attrs={'type':'date'}))

## Validation function
def check_name(value):
    if value[0].lower() != 'a':
        raise ValidationError('Name Must Start with a')
    
class empForm(forms.ModelForm):
    name = forms.CharField(validators=[check_name,MaxLengthValidator(4)])
    class Meta():
        model = employee
        fields = '__all__'
        widgets = {
            'date_of_birth':forms.DateInput(attrs={'type':'date'}),
        }

class registerform(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields=('first_name','username','email','password')
        widgets = {
            'password':forms.PasswordInput()
        }
    def clean(self):
        data = super().clean()
        name = data['first_name']
        pas = data['password']
        cp = data['confirm_password']
        if pas != cp:
            raise ValidationError('Password Does Not Match')
            
        # if name.isalnum():
        #     raise ValidationError('Name should not contain digits')

templateinherit/templates/about.html
{% extends 'base.html'%}
{% block mycode %}
<h1 class='p-5'>THIS IS ABOUT PAGE</h1>
{% endblock %}

templateinherit/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Site</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'jqueryFile.js' %}"></script>
    {% block mystyle %}
    {%endblock %}
    <style>
    .bg{
        background:url('{% static "images/img2.png"%}');
    }
    </style>
</head>
<body>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-12 px-0'>
                <nav class='navbar bg-primary navbar-expand-sm navbar-dark'>
                    <a href="{% url 'home' %}" class='navbar-brand'>MySiTe</a>
                    <ul class='navbar-nav mx-auto'>
                        <li class='nav-item'>
                            <a href="{% url 'home' %}" class='nav-link'>Home</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'mysite:ab' %}" class='nav-link'>About</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'mysite:con'%}" class='nav-link'>Contact</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'mysite:studentForm'%}" class='nav-link'>Django Form</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'admin:index' %}" class='nav-link'>Admin</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'mysite:employeeForm' %}" class='nav-link'>Model Form</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-3 bg-dark text-center py-5 text-light sticky-top'>
                <img src="{%static 'images/img4.jpg'%}" height='150' width='150' class='rounded-circle' alt="">
                <h2>Hii {{user.first_name}}</h2>
                <p>{{user.email}}</p>
                <div class='py-5'>
                    <p>View Profile</p>

                    <p><a href="{% url 'mysite:profile' %}">User profile</a></p>
                    <p><a href="{% url 'mysite:change_profile' %}">Change profile</a></p>
                    <p><a href="{% url 'mysite:change_password' %}">Change Password</a></p>
                    <p>Notifications</p>
                    <p>
                        <a href="{% url 'mysite:logout'%}">Logout</a>
                    </p>
                </div>
            </div>
            <div class='col-md-9 bg'>
                {% block mycode %}
    
                {% endblock %}
            </div>
        </div>
        <div class='row'>
        <!-- FOOTER -->
        <div class='col-md-12 bg-primary text-light py-3 text-center'>
                <h4>MySite</h4>
                <p>&copy; All rights reserved.| Designed By: Your Name</p>
            </div>
        </div>
        
    </div>
</body>
</html>

templateinherit/templates/change_password.html
{% extends "base.html" %}
{% load staticfiles %}
{% block mycode %}
<div class="row">
    <div class="col-md-6 mx-auto p-5 mt-5 bg-light">
        <form action="" method="post">
            {% csrf_token %}
            {% if status%}
            <p class="alert alert-{{col}}">{{status}}</p>
            {% endif %}
            <div class="form-group">
                <label for="">Current Password</label>
                <input type="text" class="form-control" name="old" placeholder="Current Password">
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="">New Password</label>
                        <input type="text" class="form-control" name="new" id='p' placeholder="New Password" onkeyup="check()">
                    </div>
                    <div class="col-md-6">
                        <label for="">Re-enter New Password</label>
                        <input type="text" class="form-control" name="rnew" id='cp' placeholder="Re-enter New Password" onkeyup="check()">
                    </div>
                </div>      
            </div>
            <div class="form-group">
                <input type="submit" id='change' class="btn btn-primary btn-sm btn-block" value="Change Password" disabled>
            </div>
        </form>
    </div>
</div>
<script>
function check(){
    pw  = $('#p').val();
    cpw  = $('#cp').val();
    if(pw==cpw){
        $('#p').css('border','1px solid green');
        $('#cp').css('border','1px solid green');
        $('#change').removeAttr('disabled');
    }else{
        $('#p').css('border','1px solid red');
        $('#cp').css('border','1px solid red');
        $('#change').attr('disabled','disabled');
    }
}
</script>
{% endblock %}

templateinherit/templates/change_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block mycode %}
<div class="row">
    <div class="col-md-12" style="background:url('{% static 'images/3.jpg'%}')">
        <h1 class="my-3 text-center text-light">User Profile</h1>
    </div>
    <div class="col-md-6 mx-auto" style="background:rgba(0,0,0,0.5)">
        {% if status %}
            <p class="alert alert-{{c}}">{{status}}</p>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="">First Name</label>
                        <input type="text" class="form-control" name="first" value="{{user.first_name}}">
                    </div>
                    <div class="col-md-6">
                        <label for="">Last Name</label>
                        <input type="text" class="form-control" name="last" placeholder="{{user.last_name}}">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="">Username</label>
                <input type="text" class="form-control" name="username" disabled value="{{user.username}}">
            </div>
            <div class="form-group">
                <label for="">Email</label>
                <input type="email" class="form-control" name="email" value="{{user.email}}">
            </div>
            <div class="form-group">
                
                <input type="submit" class="btn btn-primary" value="Save Changes">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templateinherit/templates/contact.html
{% extends 'base.html'%}
{% block mystyle %}
<style>
h2{font-family: 'Courier New';}
</style>
{% endblock %}
{% block mycode %}
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3430.056119523628!2d76.69247711461036!3d30.71682269345137!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee5a42944be3%3A0xb713d3a3e26a89c1!2sSachTech+Solution+Pvt.+Ltd.!5e0!3m2!1sen!2sin!4v1555050384885!5m2!1sen!2sin" width="100%" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
<div class='row'>
    <div class='col-md-6 mx-auto'>
        <h2 class='text-center text-light text-uppercase'>Give Your Feedback</h2>
        <form action="" method='post'>
            {% csrf_token %}
            {% if result %}
            <div class='form-group'>
                <span class='alert alert-info'>{{result}}
                    <a href="{% url 'home'%}">Back To Homepage</a>
                </span>
            </div>
            {% else %}
            <div class='form-group'>
                <input type="text" name='uname' placeholder='Enter Name' class='form-control'>
            </div>
            <div class='form-group'>
                <input type="email" name='email' placeholder='Enter Email ID' class='form-control'>
            </div>
            <div class='form-group'>
                <textarea name="msz" id="" class='form-control' rows="10" placeholder='Message Here'></textarea>
            </div>
            <div class='form-group'>
                <input type="submit" class='btn btn-primary btn-sm' value='Send Feedback'>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

templateinherit/templates/employee.html
{% extends 'base.html' %}
{% block mystyle %}
{% load bootstrap4 %}
<style>
h2{font-family:courier New;color:white;}
label{color:white;}
</style>
{% endblock %}
{% block mycode %}
<h2>Employee form </h2>
<div style='height:2px;width:100px;background:red;'></div>
<div class='row p-4'>
    <div class='col-md-6 mx-auto' style='background:rgba(0,0,0,0.5)'>
        {% if msz %}
            <h2 class='alert alert-{{color}}'>{{msz}}</h2>
        {% endif %}
        <form action="" method='post'>
            {% csrf_token %}
            {% bootstrap_form frm%}
            <input type="submit" class='btn btn-primary m-2'>
        </form>
    </div>
</div>
{% endblock %}

templateinherit/templates/home.html
{% extends "base.html" %}
{% block mystyle %}
<style>
    h1{
        color:red;
        font-family: cursive;
    }
</style>
{%endblock %}
{% block mycode %}

<div class='container'>
    <div class='row'>
        <div class='col-md-12 bg-light p-2'>
            <div class='card-columns'>
                {% for i in data %}
                    <div class='card'>
                        <div class='card-header'>
                            <h4>{{i.name}}</h4>
                            <span class='float-right'>- {{i.email}}</span>
                        </div>
                        <div class='card-body'>
                            <p>{{i.message}}</p>
                            <span class='text-danger'>On| {{i.feedback_date}}</span>
                        </div>
                        
                    </div>
                {% endfor %}
                </div>
        </div>
    </div>
</div>
{% endblock %}

templateinherit/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index Page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <style>
    .bg{
        background:url('{% static "images/img2.png"%}');
        background-size:cover
    }
    .btn{
        height:100px;
    }
    </style>
</head>
<body class='bg py-5'>
    <div class='container py-5 my-5'>
        <div class='row py-5 my-5'>
            <div class='col-md-6'>
                <a href="{% url 'mysite:usregister'%}">
                    <button class='btn btn-danger btn-block'>Not Have an Account?</button>
                </a>
            </div>
            <div class='col-md-6'>
                <a href="{% url 'mysite:uslogin'%}">
                    <button class='btn btn-success btn-block'>Login</button>
                </a>
            </div>
        </div>
    </div>
</body>
</html>

templateinherit/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
</head>
<body class="bg-light">
        <div class="container">
            <div class="row shadow-lg mt-5">
                <div class="col-md-6 p-5" style="background:#fff;">
                    <h1 class="mb-4 display-4">Login</h1>
                    <p>Don't have account <a href="">Create one </a> It's free and take only a minute. </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class='logininput mt-3' placeholder="Username" />
                        <input type="password" name="password" class='logininput mt-3' placeholder="Password" />
                        <br/>
                        <input type="checkbox" name='remember'> <label for="">Remember Me</label>
                        <input type="submit" value='Login' class="btn btn-success mt-5"/>
                    </form>
                    {% if status %}
                        <script>
                        alert('{{status}}');
                        </script>
                    {% endif %}
                </div>
                <div class="col-md-6" style='background:url("{% static 'images/loginimg.jpg' %}")'></div>
            </div>
        </div>
    </body>
</html>

templateinherit/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block mycode %}

<div class="row">
    <div class="col-md-12"style="background:url('{% static 'image/3.jpg'}')">
        <h1>User profile</h1>
        <table class="table">
            <tr>
                <th>username</th>
                <th>{{data.username}}</th>
            </tr>
            <tr>
                <th>First name</th>
                <th>{{data.first_name}}</th>
            </tr>
            <tr>
                <th>Last name</th>
                <th>{{data.last_name}}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{data.email}}</th>
            </tr>
            <tr>
                <th>Since username</th>
                <th>{{data.date_joined}}</th>
            </tr>
            <tr>
                <th>Last Login</th>
                <th>{{data.last_login}}</th>
            </tr>

        </table>
    </div>
    </div>
{% endblock %}

templateinherit/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration Page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="{% static 'js/jquery.js' %}"></script>
    <style>
        .logininput{
            width:100%;
            height:40px;
            border:0px;
            border-bottom:2px solid #ccc;
        }
        .logininput:focus{
            box-shadow:none;
            outline: 0px;
        }
    </style>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row shadow-lg my-5">
            <div class="col-md-6 p-5" style="background:#fff;">
                <h1 class="mb-5">Register</h1>
                <form method="post">
                    {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label>First Name</label>
                        <input type="text" class="form-control" name="first_name" />
                    </div>
                    <div class="col-md-6">
                        <label>Last Name</label>
                        <input type="text" class="form-control" name="last_name" />
                    </div>
                </div>
                <label>Username</label>
                <small class='text-danger' id='msz'></small>
                <input type="text" class="form-control" name="username" id='user'/>
                <label>Password</label>
                <input type="Password" class="form-control" name="password" />
                <label>Email</label>
                <input type="email" class="form-control" name="email" />
                <label for="">Address</label>
                <textarea class="form-control" name="address"></textarea>
                <label for="">Contact Number</label>
                <input type="number" class="form-control" name="contact" />
                <input type="submit" class="btn btn-success mt-3" />
                </form>
            </div>
            <div class="col-md-6" style='background:url("{% static 'images/loginimg.jpg' %}")'></div>
        </div>
    </div>
</body>
</html>

templateinherit/templates/registration.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register Using Django User Model Form</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <style>
    .bg{
        background: url('{% static "images/loginimg.jpg"%}');
    }
    </style>
</head> 
<body class='bg-light py-5'>
    <div class='container p-5 shadow-lg'>
        <div class='row'>
            <div class='col-md-6'>
                <form action="" method='post'>
                    {% csrf_token %}
                    {% bootstrap_form frm %}
                    <input type="submit" value='register' class='btn btn-success'>
                </form>
            </div>
            <div class='col-md-6 bg text-light text-center py-5'>
                <h2 class='my-5'>Fill Your Details</h2>
            </div>
        </div>
    </div>
    {% if status %}
    <script>
        alert('{{status}}');
    </script>
    {% endif %}
</body>
</html>

templateinherit/templates/studentForm.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block mystyle %}
    <style>
    label{
        color:blue;
    }
    /* #id_name{
        width:50%;
    } */
    </style>
{% endblock %}
{% block mycode %}
    <h1>Django Form</h1> 
    <!-- <table>
        {{form.as_table}}  
    </table>  -->
    <!-- {{form.as_p}} -->
    <div class='row'>
        <div class='col-md-8 mx-auto p-2 bg-light'>
            <form action="">
                {% bootstrap_form form %}
                <input type="submit" class='btn btn-primary'>
            </form>
        </div>
    </div>
{% endblock %}